services:
    cron.task.core.prune_all_categories:
        class: ernadoo\phpbbdirectory\cron\task\core\prune_all_categories
        arguments:
            - @dbal.conn
            - @config
            - %core.php_ext%
            - @phpbbdirectory.link
        calls:
            - [set_name, [cron.task.core.prune_all_categories]]
        tags:
            - { name: cron.task }

    cron.task.core.prune_categorie:
        class: ernadoo\phpbbdirectory\cron\task\core\prune_categorie
        arguments:
            - @dbal.conn
            - @config
            - %core.php_ext%
            - @phpbbdirectory.link
        calls:
            - [set_name, [cron.task.core.prune_categorie]]
        tags:
            - { name: cron.task }