imports:
    - { resource: tables.yml }
    - { resource: notifications.yml }
    - { resource: cron_tasks.yml }

services:
    ernadoo.phpbbdirectory.controller.categorie:
        class: ernadoo\phpbbdirectory\controller\categories
        arguments:
            - @dbal.conn
            - @config
            - @template
            - @user
            - @controller.helper
            - @request
            - @auth
            - @pagination
            - @ernadoo.phpbbdirectory.core.categorie
            - @ernadoo.phpbbdirectory.core.link
            - %core.root_path%
            - %core.php_ext%

    ernadoo.phpbbdirectory.controller.link:
        class: ernadoo\phpbbdirectory\controller\links
        arguments:
            - @dbal.conn
            - @config
            - @template
            - @user
            - @controller.helper
            - @request
            - @auth
            - @ernadoo.phpbbdirectory.core.categorie
            - @ernadoo.phpbbdirectory.core.link
            - @ernadoo.phpbbdirectory.core.helper
            - %core.root_path%
            - %core.php_ext%

    ernadoo.phpbbdirectory.controller.comment:
        class: ernadoo\phpbbdirectory\controller\comments
        arguments:
            - @dbal.conn
            - @config
            - @template
            - @user
            - @controller.helper
            - @request
            - @auth
            - @pagination
            - @ernadoo.phpbbdirectory.core.categorie
            - @ernadoo.phpbbdirectory.core.comment
            - %core.root_path%
            - %core.php_ext%

    ernadoo.phpbbdirectory.controller.search:
        class: ernadoo\phpbbdirectory\controller\search
        arguments:
            - @dbal.conn
            - @config
            - @template
            - @user
            - @controller.helper
            - @request
            - @auth
            - @pagination
            - @ernadoo.phpbbdirectory.search.fulltext
            - @ernadoo.phpbbdirectory.core.categorie
            - @ernadoo.phpbbdirectory.core.link

    ernadoo.phpbbdirectory.listener:
        class: ernadoo\phpbbdirectory\event\listener
        arguments:
            - @dbal.conn
            - @controller.helper
            - @template
            - @user
            - %core.table_prefix%
            - %core.php_ext%
        tags:
            - { name: event.listener }

    ernadoo.phpbbdirectory.core.categorie:
        class: ernadoo\phpbbdirectory\core\categorie
        arguments:
            - @dbal.conn
            - @config
            - @template
            - @user
            - @controller.helper
            - @request
            - @auth
            - @service_container
            - @ernadoo.phpbbdirectory.core.helper
            - %core.root_path%
            - %core.php_ext%

    ernadoo.phpbbdirectory.core.link:
        class: ernadoo\phpbbdirectory\core\link
        arguments:
            - @dbal.conn
            - @config
            - @template
            - @user
            - @controller.helper
            - @request
            - @auth
            - @service_container
            - @ernadoo.phpbbdirectory.core.helper
            - %core.root_path%
            - %core.php_ext%

    ernadoo.phpbbdirectory.core.comment:
        class: ernadoo\phpbbdirectory\core\comment
        arguments:
            - @dbal.conn

    ernadoo.phpbbdirectory.core.helper:
        class: ernadoo\phpbbdirectory\core\helper
        arguments:
            - @ext.manager
            - @path_helper

    ernadoo.phpbbdirectory.search.fulltext:
        class: ernadoo\phpbbdirectory\search\fulltext_directory
        arguments:
            - @dbal.conn